# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('site', models.URLField(blank=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('submission_start', models.DateTimeField(blank=True, null=True)),
                ('submission_end', models.DateTimeField(blank=True, null=True)),
                ('logo', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
