# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='logo_url',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='site_url',
            new_name='site',
        ),
        migrations.AlterField(
            model_name='conference',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.SlugField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
