# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
