# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20160712_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='city',
            field=models.CharField(default='Charlottesville', max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='state',
            field=models.CharField(default='Virginia', max_length=100),
        ),
    ]
