# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20160713_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
