# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='submission_contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
