# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='approval',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='approvals.Approval'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference'),
        ),
    ]
