# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
