# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20160726_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 7, 26, 19, 6, 13, 190688, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
