# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:24
from __future__ import unicode_literals

from django.db import migrations

from allauth.socialaccount.models import SocialApp
from django.contrib.sites.models import Site

from django.conf import settings
import meetings.settings.local as local

CLIENT_ID = local.CLIENT_ID
CLIENT_SECRET = local.CLIENT_SECRET


def make_social_app(apps, schema_editor):
    mysite = Site.objects.create(domain="osf.io", name="OSF")
    mysite.save()
    mysocialapp = SocialApp.objects.create(
        name="OSF",
        client_id=CLIENT_ID,
        secret=CLIENT_SECRET,
        key="", provider="osf")
    mysocialapp.sites.add(mysite)
    mysocialapp.save()


def create_human_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name=settings.HUMANS_GROUP_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_social_app),
        migrations.RunPython(create_human_group),
    ]
