# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('close_date', models.DateField()),
                ('logo_url', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('sponsors', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osf_id', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Meeting')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
