# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='sponsors',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
