# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('osf_id', models.UUIDField()),
                ('url_file', models.URLField()),
            ],
        ),
    ]
